/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package testmultisplitpanes;

import javax.swing.JList;


public class AtDialog extends javax.swing.JDialog {

    /**
     * Creates new form AtDialog
     */
    public AtDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainIndicatorPanel = new javax.swing.JPanel();
        IndiatorsAvaiablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SelectedPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RemoveButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        SettingsPanel = new javax.swing.JPanel();
        OkButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Analysis Techniques Manager");

        MainIndicatorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Indicators"));

        IndiatorsAvaiablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Indicators"));

        javax.swing.GroupLayout IndiatorsAvaiablePanelLayout = new javax.swing.GroupLayout(IndiatorsAvaiablePanel);
        IndiatorsAvaiablePanel.setLayout(IndiatorsAvaiablePanelLayout);
        IndiatorsAvaiablePanelLayout.setHorizontalGroup(
            IndiatorsAvaiablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        IndiatorsAvaiablePanelLayout.setVerticalGroup(
            IndiatorsAvaiablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndiatorsAvaiablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
        );
        
        String[] data = new String[]{"one", "two", "three"};
        
        javax.swing.JList<String> indicList = new javax.swing.JList<String>(data);
        
        jScrollPane1.add( indicList );

        SelectedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Indicators\n"));

        javax.swing.GroupLayout SelectedPanelLayout = new javax.swing.GroupLayout(SelectedPanel);
        SelectedPanel.setLayout(SelectedPanelLayout);
        SelectedPanelLayout.setHorizontalGroup(
            SelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        SelectedPanelLayout.setVerticalGroup(
            SelectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );

        RemoveButton.setText("Remove");

        AddButton.setText("Add");

        SettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings\n"));

        javax.swing.GroupLayout SettingsPanelLayout = new javax.swing.GroupLayout(SettingsPanel);
        SettingsPanel.setLayout(SettingsPanelLayout);
        SettingsPanelLayout.setHorizontalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        SettingsPanelLayout.setVerticalGroup(
            SettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");

        javax.swing.GroupLayout MainIndicatorPanelLayout = new javax.swing.GroupLayout(MainIndicatorPanel);
        MainIndicatorPanel.setLayout(MainIndicatorPanelLayout);
        MainIndicatorPanelLayout.setHorizontalGroup(
            MainIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                .addGroup(MainIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(AddButton)
                        .addGap(30, 30, 30)
                        .addComponent(RemoveButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainIndicatorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IndiatorsAvaiablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SelectedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(MainIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(CancelButton)
                        .addGap(26, 26, 26)
                        .addComponent(OkButton))
                    .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainIndicatorPanelLayout.setVerticalGroup(
            MainIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                        .addComponent(SettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(MainIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OkButton)
                            .addComponent(CancelButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MainIndicatorPanelLayout.createSequentialGroup()
                        .addComponent(IndiatorsAvaiablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(MainIndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveButton)
                            .addComponent(AddButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SelectedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainIndicatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainIndicatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_OkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AtDialog dialog = new AtDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JPanel IndiatorsAvaiablePanel;
    private javax.swing.JPanel MainIndicatorPanel;
    private javax.swing.JButton OkButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JPanel SelectedPanel;
    private javax.swing.JPanel SettingsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
